version: '3.10'

services:
  python-flask-app-container:
    image: contactsapp
    container_name: python-flask-app-container
    ports:
      - 3000:3000
    volumes:
      - $pwd/app
#    networks:
#      - mysql-python-app-network
  
  mysql-flask-app-container:
      image: mysql:8.0
      container_name: mysql-flask-app-container 
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 12345
